server:
  port: ${PORT:8080}

spring:
  application:
    name: YouTubeWatchParty

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/youtubewatchparty}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    generate-ddl: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

frontend:
  url: ${FRONTEND_URL:http://localhost:5173,https://youtube-watch-party-frontend-p9ww.onrender.com}