CREATE TABLE rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_code VARCHAR(10) NOT NULL,
    host_user_id VARCHAR(255) NOT NULL,
    video_id VARCHAR(255) NOT NULL,
    playing BOOLEAN NOT NULL,
    current_time_seconds DOUBLE PRECISION NOT NULL,
    last_state_updated_at BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE UNIQUE INDEX idx_room_code ON rooms(room_code);

CREATE TABLE participants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(255) NOT NULL,
    username VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL,
    room_code VARCHAR(255) NOT NULL,
    is_online BOOLEAN NOT NULL,
    joined_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE UNIQUE INDEX idx_user_room ON participants(user_id, room_code);

CREATE INDEX idx_room_code_part ON participants(room_code);
